[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "https://microfe-poc.netlify.app"
        Access-Control-Allow-Methods = "GET, OPTIONS"
        Access-Control-Allow-Headers = "Content-Type"
